# Generated by Django 5.0.1 on 2024-01-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_chattypes_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.BooleanField()),
                ('admin', models.BooleanField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.chats')),
            ],
            options={
                'db_table': 'roles',
                'unique_together': {('id', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.chats')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.users')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.roles')),
            ],
            options={
                'db_table': 'members',
                'unique_together': {('user_id', 'chat_id', 'role_id')},
            },
        ),
    ]
