# Generated by Django 5.0.1 on 2024-01-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_rename_type_id_chats_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='config.chattypes'),
        ),
    ]
