# Generated by Django 5.0.1 on 2024-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_users_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
