# Generated by Django 5.0.1 on 2024-02-02 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_alter_users_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 23, 16, 15, 135055, tzinfo=datetime.timezone.utc)),
        ),
    ]
