# Generated by Django 5.0.1 on 2024-03-01 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_users_expiry_date_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 13, 1, 31, 909170, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
