# Generated by Django 5.0.1 on 2024-03-07 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_alter_users_expiry_date_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 17, 38, 45640, tzinfo=datetime.timezone.utc)),
        ),
    ]
