# Generated by Django 5.0.1 on 2024-03-07 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_alter_chats_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 8, 42, 32, 423930, tzinfo=datetime.timezone.utc)),
        ),
    ]
