# Generated by Django 5.0.1 on 2024-03-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_alter_users_expiry_date_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 8, 44, 24, 331560, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
