# Generated by Django 5.0.1 on 2024-03-15 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_events_subscriptions_alter_users_expiry_date_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chattypes',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='users',
            name='expiry_date_code',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 17, 5, 37, 641354, tzinfo=datetime.timezone.utc)),
        ),
    ]
